# Generated by Django 4.2.4 on 2023-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_emailer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='event',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='event_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
