# Generated by Django 4.2.4 on 2023-09-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_emailer_app', '0002_remove_emaillog_event_emaillog_event_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailLog',
            new_name='EventLog',
        ),
    ]
